services:
  jenkins:
    image: qa-jenkins
    container_name: jenkins
    ports:
      - "8080:8080"
    networks:
      - jenkins-network

  selenium-hub:
    image: seleniarm/hub:latest
    container_name: selenium-hub
    ports:
      - "4444:4444"
      - "50000:50000"
    networks:
      - jenkins-network
    volumes:
      - ${HOME}/jenkins_compose/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  chrome-node:
    image: seleniarm/node-chromium:latest
    container_name: chrome-node
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - jenkins-network

  firefox-node:
    image: seleniarm/node-firefox:latest
    container_name: firefox-node
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - jenkins-network

networks:
  jenkins-network:
    name: jenkins-network
    external: true


